#!/bin/bash
# clean-packagexml.sh
# Removes unwanted metadata types from packagexmlfull.xml
# Run from the root of your SF-CICD-HARDIS project

INPUT="./packagexmlfull.xml"
OUTPUT="./packagexmlfull-clean.xml"

# List of metadata types to DELETE
TYPES_TO_DELETE=(
  "ActivationPlatform"
  "AnalyticsWorkspace"
  "AnimationRule"
  "AppMenu"
  "Audience"
  "AuthProvider"
  "CallCenter"
  "CanvasMetadata"
  "Certificate"
  "CleanDataService"
  "Community"
  "ConnectedApp"
  "DataConnectorIngestApi"
  "DataKitObjectDependency"
  "DataKitObjectTemplate"
  "DataPackageKitDefinition"
  "DataPackageKitObject"
  "DataSource"
  "DataSourceBundleDefinition"
  "DataSourceObject"
  "DataSourceTenant"
  "DataSrcDataModelFieldMap"
  "DataStreamDefinition"
  "DataStreamTemplate"
  "DigitalExperience"
  "DigitalExperienceConfig"
  "EmailServicesFunction"
  "ExtDataTranObjectTemplate"
  "ExternalAuthIdentityProvider"
  "ExternalClientApplication"
  "ExternalDataConnector"
  "ExternalDataTranObject"
  "ExtlClntAppConfigurablePolicies"
  "ExtlClntAppGlobalOauthSettings"
  "ExtlClntAppOauthConfigurablePolicies"
  "ExtlClntAppOauthSettings"
  "FeatureParameterBoolean"
  "FieldRestrictionRule"
  "FieldSrcTrgtRelationship"
  "FlowDefinition"
  "ForecastingType"
  "GenAiPlannerBundle"
  "Group"
  "HomePageLayout"
  "IframeWhiteListUrlSettings"
  "InstalledPackage"
  "InternalDataConnector"
  "KeywordList"
  "LeadConvertSettings"
  "ManagedContentType"
  "ManagedTopics"
  "MarketSegmentDefinition"
  "MktCalcInsightObjectDef"
  "MktDataConnection"
  "MktDataTranObject"
  "ModerationRule"
  "NotificationTypeConfig"
  "ObjectSourceTargetMap"
  "PlatformCachePartition"
  "PlatformEventChannelMember"
  "ProfilePasswordPolicy"
  "ProfileSessionSetting"
  "SiteDotCom"
  "StandardValueSet"
  "TopicsForObjects"
  "UiFormatSpecificationSet"
  "UiViewDefinition"
  "UserCriteria"
  "UserProvisioningConfig"
  "WebLink"
)

echo "🧹 Cleaning $INPUT..."
cp "$INPUT" "$OUTPUT"

for TYPE in "${TYPES_TO_DELETE[@]}"; do
  # Remove the entire <types>...</types> block for each metadata type
  perl -0777 -i -pe "s|<types>\s*(?:<members>[^<]*</members>\s*)*<name>${TYPE}<\/name>\s*<\/types>||g" "$OUTPUT"
  echo "  ❌ Removed: $TYPE"
done

echo ""
echo "✅ Done! Cleaned file saved as: $OUTPUT"
echo ""
echo "📊 Item count in cleaned file:"
grep "<members>" "$OUTPUT" | wc -l