#!/bin/bash
# clean-layouts.sh
# Deletes standard/uncustomized layouts, keeps custom object layouts (__c, __mdt)
# and customized standard object layouts
# Run from the root of your SF-CICD-HARDIS project

LAYOUTS_DIR="./force-app/main/default/layouts"

# Standard layouts to DELETE (uncustomized default layouts)
LAYOUTS_TO_DELETE=(
  "Account-Account Layout.layout-meta.xml"
  "AccountBrand-Account Brand Layout.layout-meta.xml"
  "AccountContactRelation-Account Contact Relationship Layout.layout-meta.xml"
  "AccountTeamMember-Présentation Membre de l%27équipe du compte.layout-meta.xml"
  "ActionPlan-Présentation Plan d%27action.layout-meta.xml"
  "ActionPlanItemDependency-Présentation Dépendance d%27élément de plan d%27action.layout-meta.xml"
  "ActionPlanTemplate-Présentation Modèle de plan d%27action.layout-meta.xml"
  "ActionPlanTemplateItem-Présentation Élément de modèle de plan d%27action.layout-meta.xml"
  "ActionPlanTemplateItemValue-Présentation Valeur d%27élément de modèle de plan d%27action.layout-meta.xml"
  "ActionPlanTemplateVersion-Présentation Version de modèle de plan d%27action.layout-meta.xml"
  "ActionPlnTmplItmDependency-Présentation Dépendance d%27élément de modèle de plan d%27action.layout-meta.xml"
  "AlternativePaymentMethod-Présentation Mode de paiement alternatif.layout-meta.xml"
  "Asset-Asset Layout.layout-meta.xml"
  "AssetRelationship-Asset Relationship Layout.layout-meta.xml"
  "AssociatedLocation-Présentation Emplacement associé.layout-meta.xml"
  "AuthorizationForm-Présentation Formulaire d%27autorisation.layout-meta.xml"
  "AuthorizationFormConsent-Présentation Consentement du formulaire d%27autorisation.layout-meta.xml"
  "AuthorizationFormDataUse-Présentation Utilisation des données du formulaire d%27autorisation.layout-meta.xml"
  "AuthorizationFormText-Présentation Texte du formulaire d%27autorisation.layout-meta.xml"
  "BusinessBrand-Présentation Marque commerciale.layout-meta.xml"
  "Campaign-Campaign Layout.layout-meta.xml"
  "CampaignMember-Campaign Member Page Layout.layout-meta.xml"
  "CampaignMemberStatus-Présentation Statut de membre de campagne.layout-meta.xml"
  "CardPaymentMethod-Présentation Mode de paiement par carte.layout-meta.xml"
  "Case-Case Layout.layout-meta.xml"
  "CaseClose-Close Case Layout.layout-meta.xml"
  "CaseInteraction-Case Feed Layout.layout-meta.xml"
  "ChannelProgram-Présentation Programme canal.layout-meta.xml"
  "ChannelProgramLevel-Présentation Niveau de programme canal.layout-meta.xml"
  "CollaborationGroup-Group Layout.layout-meta.xml"
  "Contact-Contact Layout.layout-meta.xml"
  "ContactPointAddress-Présentation Adresse du point de contact.layout-meta.xml"
  "ContactPointEmail-Présentation Adresse e-mail du point de contact.layout-meta.xml"
  "ContactPointPhone-Présentation Téléphone du point de contact.layout-meta.xml"
  "ContactPointTypeConsent-Présentation Consentement du type de point de contact.layout-meta.xml"
  "ContactRequest-Présentation Requête de contact.layout-meta.xml"
  "ContentAsset-Asset File Layout.layout-meta.xml"
  "ContentVersion-Content Version.layout-meta.xml"
  "Contract-Contract Layout.layout-meta.xml"
  "CreditMemo-Présentation Note de crédit.layout-meta.xml"
  "CreditMemoLine-Présentation Ligne de note de crédit.layout-meta.xml"
  "CspTrustedSite-Trusted URL Layout.layout-meta.xml"
  "Customer-Présentation Client.layout-meta.xml"
  "DataGraph-Présentation Graphique de données.layout-meta.xml"
  "DataLakeObjectInstance-Data Lake Object Layout.layout-meta.xml"
  "DataSpace-Présentation Espace de données.layout-meta.xml"
  "DataStream-Data Stream Layout.layout-meta.xml"
  "DataStreamDefinition-Data Stream Definition Layout.layout-meta.xml"
  "DataUseLegalBasis-Présentation Base juridique de traitement des données.layout-meta.xml"
  "DataUsePurpose-Présentation Objectif d%27utilisation des données.layout-meta.xml"
  "DelegatedAccount-Présentation du compte géré externe.layout-meta.xml"
  "DigitalWallet-Présentation Digital Wallet.layout-meta.xml"
  "DuplicateRecordItem-Duplicate Record Item Layout.layout-meta.xml"
  "DuplicateRecordSet-Duplicate Record Set Layout.layout-meta.xml"
  "EmailContent-Présentation Contenu d%27e-mail.layout-meta.xml"
  "EmailMessage-Email Message Layout.layout-meta.xml"
  "Event-Event Layout.layout-meta.xml"
  "ExtDataShare-Présentation Partage de données.layout-meta.xml"
  "FeedItem-Feed Item Layout.layout-meta.xml"
  "FlowInterview-Flow Interview Layout.layout-meta.xml"
  "FlowOrchestrationWorkItem-Présentation Élément de travail de l%27orchestration.layout-meta.xml"
  "FlowRecord-Flow Layout.layout-meta.xml"
  "Global-Global Layout.layout-meta.xml"
  "Idea-Idea Layout.layout-meta.xml"
  "IdentityResolution-Identity Resolution Layout.layout-meta.xml"
  "Image-Présentation Image.layout-meta.xml"
  "Individual-Présentation Individu.layout-meta.xml"
  "Invoice-Présentation Facture.layout-meta.xml"
  "InvoiceLine-Présentation Ligne de facture.layout-meta.xml"
  "Lead-Lead Layout.layout-meta.xml"
  "ListEmail-Présentation E-mail de liste.layout-meta.xml"
  "Location-Présentation Emplacement.layout-meta.xml"
  "Macro-Macro Layout.layout-meta.xml"
  "ManagedContent-Présentation Contenu géré.layout-meta.xml"
  "ManagedContentVariant-Contenu géré.layout-meta.xml"
  "MarketSegment-Segment Layout.layout-meta.xml"
  "MessagingChannel-Messaging Channel Layout.layout-meta.xml"
  "MessagingEndUser-Messaging User Layout.layout-meta.xml"
  "MktDataTransform-Data Transform Layout.layout-meta.xml"
  "Opportunity-Opportunity Layout.layout-meta.xml"
  "OpportunityContactRole-Présentation Rôle des contacts de l%27opportunité.layout-meta.xml"
  "OpportunityLineItem-Opportunity Product Layout.layout-meta.xml"
  "OpportunityTeamMember-Opportunity Team Member Layout.layout-meta.xml"
  "Order-Order Layout.layout-meta.xml"
  "OrderItem-Order Product Layout.layout-meta.xml"
  "OutgoingEmail-Outgoing Email Layout.layout-meta.xml"
  "Outlook-Gmail Integration and Sync.layout-meta.xml"
  "Payment-Présentation Paiement.layout-meta.xml"
  "PaymentAuthAdjustment-Présentation Ajustement de l%27autorisation de paiement.layout-meta.xml"
  "PaymentAuthorization-Présentation Autorisation de paiement.layout-meta.xml"
  "PaymentGateway-Présentation Passerelle de paiement.layout-meta.xml"
  "PaymentGatewayLog-Présentation Journal de passerelle de paiement.layout-meta.xml"
  "PaymentGroup-Présentation Groupe de paiement.layout-meta.xml"
  "PaymentLineInvoice-Présentation Facture de la ligne de paiement.layout-meta.xml"
  "Pricebook2-Price Book Layout.layout-meta.xml"
  "PricebookEntry-Price Book Entry Layout.layout-meta.xml"
  "ProcessException-Présentation Exception de traitement.layout-meta.xml"
  "Product2-Product Layout.layout-meta.xml"
  "ProfileSkill-Skill Layout.layout-meta.xml"
  "ProfileSkillEndorsement-Endorsement Layout.layout-meta.xml"
  "ProfileSkillUser-Skill User Layout.layout-meta.xml"
  "Prospect-Présentation Prospect.layout-meta.xml"
  "QuickText-Quick Text Layout.layout-meta.xml"
  "Quote-Quote Layout.layout-meta.xml"
  "QuoteLineItem-Quote Line Item Layout.layout-meta.xml"
  "ReceivedDocument-Présentation Document reçu.layout-meta.xml"
  "ReceivedDocumentType-Présentation Type de documents reçu.layout-meta.xml"
  "Refund-Présentation Remboursement.layout-meta.xml"
  "RefundLinePayment-Présentation Paiement de la ligne de remboursement.layout-meta.xml"
  "SalesforceContract-Salesforce Contract Layout.layout-meta.xml"
  "SalesforceInvoice-Salesforce Invoice Layout.layout-meta.xml"
  "SalesforceQuote-Salesforce Quote Layout.layout-meta.xml"
  "Scorecard-Scorecard Layout.layout-meta.xml"
  "ScorecardAssociation-Scorecard Association Layout.layout-meta.xml"
  "ScorecardMetric-Scorecard Metric Layout.layout-meta.xml"
  "Seller-Présentation Vendeur.layout-meta.xml"
  "SiqExchangeConnection-Présentation Connexion Exchange.layout-meta.xml"
  "SocialPersona-Social Persona Layout.layout-meta.xml"
  "SocialPost-Social Post Layout.layout-meta.xml"
  "Solution-Solution Layout.layout-meta.xml"
  "Task-Task Layout.layout-meta.xml"
  "User-User Layout.layout-meta.xml"
  "UserAlt-User Profile Layout.layout-meta.xml"
  "UserAppMenuItem-Application Layout.layout-meta.xml"
  "UserProvAccount-User Provisioning Account Layout.layout-meta.xml"
  "UserProvisioningLog-User Provisioning Log Layout.layout-meta.xml"
  "UserProvisioningRequest-User Provisioning Request Layout.layout-meta.xml"
  "WorkAccess-Access Layout.layout-meta.xml"
  "WorkBadge-Badge Layout.layout-meta.xml"
  "WorkBadge-Badge Received Layout 192.layout-meta.xml"
  "WorkBadgeDefinition-Badge Definition Layout.layout-meta.xml"
  "WorkBadgeDefinition-Badge Layout 192.layout-meta.xml"
  "WorkThanks-Thanks Layout.layout-meta.xml"
)

echo "🧹 Cleaning standard layouts from $LAYOUTS_DIR..."
DELETED=0
NOT_FOUND=0

for LAYOUT in "${LAYOUTS_TO_DELETE[@]}"; do
  FILE="$LAYOUTS_DIR/$LAYOUT"
  if [ -f "$FILE" ]; then
    rm "$FILE"
    echo "  ❌ Deleted: $LAYOUT"
    ((DELETED++))
  else
    ((NOT_FOUND++))
  fi
done

echo ""
echo "✅ Done!"
echo "   Deleted:   $DELETED layouts"
echo "   Not found: $NOT_FOUND layouts (already removed or renamed)"
echo ""
echo "📋 Remaining layouts (custom/customized - KEPT):"
ls "$LAYOUTS_DIR/"