mergeTargets:
  - PreProd
targetUsername: m.curpen-external@alliancedesenergies.fr.ellisphere
instanceUrl: https://alliancedesenergies--ellisphere.sandbox.my.salesforce.com
branchesToMergeBack:
  - dev_Hassan
  - dev_Elkhamis
  - dev_Moganaden
  - dev_Jerome
  - dev_Ali
