public with sharing class RebranchGitTest {
    public RebranchGitTest() {
        System.debug('MOGANADEN2');
        System.debug('MOGANADEN3');
        System.debug('MOGANADEN4');
        System.debug('MOGANADEN5');


         System.debug('MOGANADN6');
         System.debug('MOGANADN7');


        System.debug('MOGANADN8');


        System.debug('MOGANADN9');

         System.debug('MOGANADN10');
        // HERE THE TEST CLASS CODE weds fedsxzsa
        // fsaxz
        //xzcjjsb dmascjlxhvj
    }
}